### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by AntGrimm** [AntGrimm/assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary
- [x] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [x] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [x] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [x] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [x] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [x] Upload or submit a link to your resume for review.

**Comment by AntGrimm** [comment]
https://anthonygrimm.com/images/AnthonyGrimmResume.pdf

**Comment by ktrammell95** [comment]
Tony, Your resume looks great. I would definitely see if you can make the info for your portfolio, LinkedIn, and GitHub into links for when people look at it on a computer but other all excel layout and information. I would like to see some projects to support your tech knowledge but I can see why you didn't add them since they would knock you to a second page.

See what the recruiters think and if they call out the same things about projects then really consider it.

 ![Screen Shot 2019-09-26 at 10 32 28 AM](https://user-images.githubusercontent.com/10440779/65697466-fb4e7180-e048-11e9-94c5-021e39d0f1f6.png)
